### ISSUE TITLE
Only 187 human annotations on the validation set

### ISSUE THREAD

**Issue by ycwu1997** [rajpurkarlab/cheXlocalize#9]
Dear authors,

Thanks for your work. I have accessed your proposed dataset and found only 170 patients' images (#: 187) on the validation set. Is this correct? The annotations are in the gt_annotations_val.json file. 
Could you please check it?

Thanks,
Eli

**Comment by asaporta** [comment]
Hi Eli!

That's correct: there should be 187 subjects with annotations (and 643 annotations total) in `gt_annotations_val.json`. That's because this json file should include only those CXRs with at least one positive ground-truth label, and each CXR in the json should include only those pathologies for which its ground-truth label is positive.

I'll make sure to add this to the README now, so it's clear :)

Thanks!
Adriel

**Comment by ycwu1997** [comment]
Got it. Thanks for your quick and kind reply.
